# core/report_generator.py — T17 Report Generator

import os
from datetime import datetime

REPORT_DIR = "reports"

def generate_report(scan_results: list, logs_analysed: int, source: str = "unknown") -> str:
    os.makedirs(REPORT_DIR, exist_ok=True)

    timestamp = datetime.now()
    filename  = f"T17_Report_{timestamp.strftime('%Y-%m-%d_%H-%M-%S')}.txt"
    filepath  = os.path.join(REPORT_DIR, filename)

    threats = [r for r in scan_results if r.get("status") == "threat_report"]

    severity_counts = {"critical": 0, "high": 0, "medium": 0, "low": 0, "unknown": 0}
    for t in threats:
        sev = t.get("severity", "unknown").lower()
        severity_counts[sev] = severity_counts.get(sev, 0) + 1

    if severity_counts["critical"] > 0:
        overall_risk   = "CRITICAL"
        recommendation = "Immediate investigation and response required."
    elif severity_counts["high"] > 0:
        overall_risk   = "HIGH"
        recommendation = "Urgent investigation recommended."
    elif severity_counts["medium"] > 0:
        overall_risk   = "MEDIUM"
        recommendation = "Investigation recommended within 24 hours."
    elif severity_counts["low"] > 0:
        overall_risk   = "LOW"
        recommendation = "Monitor the flagged events."
    else:
        overall_risk   = "NONE"
        recommendation = "No significant threats detected. Continue monitoring."

    div  = "=" * 60
    thin = "-" * 60
    lines = []

    lines.append(div)
    lines.append("  T17 THREAT INTELLIGENCE REPORT")
    lines.append("  Offline AI-Powered Cybersecurity Framework")
    lines.append(div)
    lines.append(f"  Generated:     {timestamp.strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"  Source:        {source}")
    lines.append(f"  Logs analysed: {logs_analysed}")
    lines.append(f"  Threats found: {len(threats)}")
    lines.append(f"  Overall risk:  {overall_risk}")
    lines.append(div)

    if not threats:
        lines.append("")
        lines.append("  No threats detected in this scan.")
        lines.append("")
    else:
        for i, threat in enumerate(threats, 1):
            mitre = threat.get("mitre", {})
            raw   = threat.get("reasoning", "")
            short = raw[:300].replace("\n", " ").strip()
            if len(raw) > 300:
                short += "..."

            lines.append("")
            lines.append(f"  THREAT {i}")
            lines.append(thin)
            lines.append(f"  Timestamp:   {threat.get('timestamp', 'unknown')}")
            lines.append(f"  Model used:  {threat.get('model_used', 'unknown')}")
            lines.append(f"  Severity:    {threat.get('severity', 'unknown').upper()}")
            lines.append(f"  Confidence:  {threat.get('confidence', 0)}/100")
            lines.append(f"  MITRE ID:    {mitre.get('id', 'unknown')} — {mitre.get('name', 'unknown')}")
            lines.append(f"  Tactic:      {mitre.get('tactic', 'unknown')}")
            lines.append(f"  Verdict:     {threat.get('verdict', 'unknown')}")
            lines.append("")
            lines.append(f"  Reasoning:")
            lines.append(f"  {short}")
            lines.append("")

    lines.append(div)
    lines.append("  SUMMARY")
    lines.append(thin)
    lines.append(f"  Critical: {severity_counts['critical']}")
    lines.append(f"  High:     {severity_counts['high']}")
    lines.append(f"  Medium:   {severity_counts['medium']}")
    lines.append(f"  Low:      {severity_counts['low']}")
    lines.append("")
    lines.append(f"  Recommendation: {recommendation}")
    lines.append(div)
    lines.append("")
    lines.append("  Generated by T17 — Offline AI Cybersecurity Framework")
    lines.append("  100% Local  •  No Cloud  •  MITRE ATT&CK Mapped")
    lines.append(div)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return filepath